### ISSUE TITLE
[Bug] Errors upgrading to v1.0.4

### ISSUE THREAD

**Issue by aitchiss** [storybookjs/addon-webpack5-compiler-swc#7]
With v1.0.4 latest changes (https://github.com/storybookjs/addon-webpack5-compiler-swc/pull/6) I'm seeing errors building storybook:

```
Module build failed (from ./node_modules/swc-loader/src/index.js):
Error: `env` and `jsc.target` cannot be used together
```

We're using storybook version 8.1.10 - is this something unique to our set up, or are you seeing the same?

**Comment by mcneiljv** [comment]
Seeing the exact same issue. Downgrading to 1.0.3 fixes it.

**Comment by dburles** [comment]
Same issue here.

**Comment by dburles** [comment]
My solution was to split up the configuration `.swcrc` for Storybook and `.swcrc-source` for the built source, passing it with the ` --config-file` cli argument.

**Comment by valentinpalkovic** [comment]
Storybook's default SWC config can now be overridden and customized due to this work:
https://github.com/storybookjs/addon-webpack5-compiler-swc/pull/13

Closing the issue
